import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { AuthManager } from './auth-manager';

describe('AuthManager', () => {
  describe('validateToken', () => {
    it('rejects an empty string token', () => {
      const authManager = new AuthManager();

      const isValid = authManager.validateToken('');

      expect(isValid).toBe(false);
    });

    it('accepts the token generated by the same instance', () => {
      const authManager = new AuthManager(() => 'a'.repeat(64));

      const isValid = authManager.validateToken('a'.repeat(64));

      expect(isValid).toBe(true);
    });

    it('rejects a token with incorrect length', () => {
      const authManager = new AuthManager(() => 'a'.repeat(64));

      const isValid = authManager.validateToken('a'.repeat(32));

      expect(isValid).toBe(false);
    });

    it('rejects a token with non-hex characters', () => {
      const authManager = new AuthManager(() => 'a'.repeat(64));

      const isValid = authManager.validateToken('z'.repeat(64));

      expect(isValid).toBe(false);
    });
  });

  describe('getToken', () => {
    it('returns different tokens for two instances without injection', () => {
      const firstManager = new AuthManager();
      const secondManager = new AuthManager();

      expect(firstManager.getToken()).not.toBe(secondManager.getToken());
    });
  });

  describe('tokenGenerator injection', () => {
    it('uses a deterministic token when a custom generator is provided', () => {
      const fixedToken = 'f'.repeat(64);
      const authManager = new AuthManager(() => fixedToken);

      expect(authManager.getToken()).toBe(fixedToken);
    });
  });

  describe('extractTokenFromRequest', () => {
    it('returns the token when the header has a valid Bearer format', () => {
      const authManager = new AuthManager();

      const token = authManager.extractTokenFromRequest('Bearer abc123');

      expect(token).toBe('abc123');
    });

    it('returns null when the authorization header is absent', () => {
      const authManager = new AuthManager();

      const token = authManager.extractTokenFromRequest(undefined);

      expect(token).toBeNull();
    });

    it('returns null when the authorization header does not start with Bearer', () => {
      const authManager = new AuthManager();

      const token = authManager.extractTokenFromRequest('Basic abc123');

      expect(token).toBeNull();
    });

    it('returns an empty string when the header is "Bearer " with nothing after the space', () => {
      const authManager = new AuthManager();

      const token = authManager.extractTokenFromRequest('Bearer ');

      expect(token).toBe('');
    });
  });

  describe('regenerateToken', () => {
    it('returns a new token that differs from the original', () => {
      const callCount = { value: 0 };
      const authManager = new AuthManager(() => {
        callCount.value++;
        return callCount.value === 1 ? 'a'.repeat(64) : 'b'.repeat(64);
      });

      const newToken = authManager.regenerateToken();

      expect(newToken).toBe('b'.repeat(64));
    });

    it('updates the stored token so validateToken accepts the new one', () => {
      const callCount = { value: 0 };
      const authManager = new AuthManager(() => {
        callCount.value++;
        return callCount.value === 1 ? 'a'.repeat(64) : 'b'.repeat(64);
      });

      authManager.regenerateToken();

      expect(authManager.validateToken('b'.repeat(64))).toBe(true);
      expect(authManager.validateToken('a'.repeat(64))).toBe(false);
    });
  });

  describe('validateFilePermissions', () => {
    it('returns true for a file with 0o600 permissions', () => {
      const authManager = new AuthManager();
      const tempFile = path.join(os.tmpdir(), `auth-manager-test-${Date.now()}.txt`);
      fs.writeFileSync(tempFile, 'data');
      fs.chmodSync(tempFile, 0o600);

      const isValid = authManager.validateFilePermissions(tempFile);

      fs.unlinkSync(tempFile);
      expect(isValid).toBe(true);
    });

    it('returns false for a file with world-readable permissions', () => {
      const authManager = new AuthManager();
      const tempFile = path.join(os.tmpdir(), `auth-manager-test-${Date.now()}.txt`);
      fs.writeFileSync(tempFile, 'data');
      fs.chmodSync(tempFile, 0o644);

      const isValid = authManager.validateFilePermissions(tempFile);

      fs.unlinkSync(tempFile);
      expect(isValid).toBe(false);
    });

    it('returns false when the file does not exist', () => {
      const authManager = new AuthManager();

      const isValid = authManager.validateFilePermissions('/nonexistent/path/file.txt');

      expect(isValid).toBe(false);
    });
  });
});
